import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

function buildHealthReportHTML({ patient, records = [], medications = [] }) {
  const recordRows = records.map((r) => `
    <tr>
      <td>${r.title || '-'}</td>
      <td>${r.record_type || '-'}</td>
      <td>${r.record_date || '-'}</td>
      <td>${r.notes || '-'}</td>
    </tr>
  `).join('');

  const medRows = medications.map((m) => `
    <tr>
      <td>${m.medicine_name || '-'}</td>
      <td>${m.dosage || '-'}</td>
      <td>${m.time || '-'}</td>
    </tr>
  `).join('');

  return `
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="UTF-8">
    <style>
      body { font-family: Arial, sans-serif; padding: 24px; color: #1f2937; }
      h1 { color: #0d9488; font-size: 24px; margin-bottom: 4px; }
      .subtitle { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
      .info-row { display: flex; gap: 24px; margin-bottom: 24px; }
      .info-box { background: #f0fdfa; border: 1px solid #ccfbf1; border-radius: 8px; padding: 12px 16px; }
      .info-label { font-size: 11px; color: #0d9488; font-weight: bold; text-transform: uppercase; }
      .info-value { font-size: 18px; font-weight: bold; color: #1f2937; margin-top: 2px; }
      h2 { font-size: 16px; color: #1f2937; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; margin: 24px 0 12px; }
      table { width: 100%; border-collapse: collapse; font-size: 13px; }
      th { background: #0d9488; color: white; padding: 10px; text-align: left; }
      td { padding: 9px 10px; border-bottom: 1px solid #f3f4f6; }
      tr:nth-child(even) td { background: #f9fafb; }
      .footer { margin-top: 36px; text-align: center; color: #9ca3af; font-size: 12px; }
      .empty { color: #9ca3af; font-style: italic; padding: 12px 0; }
    </style>
  </head>
  <body>
    <h1>🏥 Digital Chikitsak</h1>
    <p class="subtitle">Patient Health Report — Generated on ${new Date().toLocaleDateString('en-IN')}</p>
    <div class="info-row">
      <div class="info-box">
        <div class="info-label">Patient Name</div>
        <div class="info-value">${patient?.name || 'Unknown'}</div>
      </div>
      <div class="info-box">
        <div class="info-label">Phone</div>
        <div class="info-value">${patient?.phone || '-'}</div>
      </div>
      <div class="info-box">
        <div class="info-label">Age</div>
        <div class="info-value">${patient?.age ? `${patient.age} years` : '-'}</div>
      </div>
    </div>

    <h2>📋 Health Records</h2>
    ${records.length === 0
      ? '<p class="empty">No health records found.</p>'
      : `<table><thead><tr><th>Title</th><th>Type</th><th>Date</th><th>Notes</th></tr></thead><tbody>${recordRows}</tbody></table>`}

    <h2>💊 Medication Reminders</h2>
    ${medications.length === 0
      ? '<p class="empty">No medications found.</p>'
      : `<table><thead><tr><th>Medicine</th><th>Dosage</th><th>Time</th></tr></thead><tbody>${medRows}</tbody></table>`}

    <div class="footer">
      This report was generated by Digital Chikitsak App.<br>
      For medical advice, always consult a qualified doctor.
    </div>
  </body>
  </html>`;
}

export async function exportHealthReport({ patient, records, medications }) {
  const html = buildHealthReportHTML({ patient, records, medications });
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: 'application/pdf',
    dialogTitle: 'Health Report Share Karein',
    UTI: 'com.adobe.pdf',
  });
}

export function buildConsultationHTML({ patient, symptoms, triageResult, mlResult }) {
  return `
  <!DOCTYPE html><html><head><meta charset="UTF-8">
  <style>
    body{font-family:Arial;padding:24px;color:#1f2937}
    h1{color:#0d9488}
    .badge{display:inline-block;padding:4px 12px;border-radius:20px;font-weight:bold;font-size:13px}
    .tag{background:#f0fdfa;color:#0d9488;padding:4px 10px;border-radius:12px;margin:3px;display:inline-block;font-size:13px}
  </style></head><body>
  <h1>🩺 Consultation Summary</h1>
  <p><b>Patient:</b> ${patient?.name || 'N/A'} | <b>Date:</b> ${new Date().toLocaleDateString('en-IN')}</p>
  <h2>Symptoms Reported</h2>
  <p>${symptoms.map((s) => `<span class="tag">${s.replace(/_/g,' ')}</span>`).join(' ')}</p>
  ${mlResult ? `<h2>AI Analysis</h2><p><b>Possible Condition:</b> ${mlResult.predicted_disease}</p><p><b>Confidence:</b> ${mlResult.confidence}%</p>` : ''}
  ${triageResult ? `<h2>Priority</h2><p>${triageResult.priority?.toUpperCase()} — ${triageResult.reasoning}</p>` : ''}
  <p style="margin-top:32px;color:#9ca3af;font-size:12px">Always consult a doctor for proper diagnosis.</p>
  </body></html>`;
}

export async function exportConsultation({ patient, symptoms, triageResult, mlResult }) {
  const html = buildConsultationHTML({ patient, symptoms, triageResult, mlResult });
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Consultation Share Karein' });
}
